### ISSUE TITLE
Not finding subtitles for certains TV Shows

### ISSUE THREAD

**Issue by PaulGitProject** [josdion/subbuzz#3]
Hello, i've installed and setting up Subbuzz, but it seems to struggle finding certains subtitles. 
For example, for the TV Shows called "The Suite Life of Zack and Cody", it does not find any subtitles (no matter the episode) : 

![image](https://user-images.githubusercontent.com/29106016/228389535-7533b2f5-6d90-472b-99dd-20b6a56f34da.png)

But, if you try to search for them manually on https://www.podnapisi.net for example, you can find them : 

![image](https://user-images.githubusercontent.com/29106016/228389747-56a2af51-48bc-4f80-a768-77d325ed1f4f.png)

(PS:  It works on other tv shows / movies) 

Voila voila, thanks in advance :)

**Comment by josdion** [comment]
@PaulGitProject Hello! Can you look at jellyfin log to see what is the error? On what OS is running jellyfin?

**Comment by PaulGitProject** [comment]
> @PaulGitProject Please also check what is the Original title of this TV Show -> select the TV Show and click on Edit Metadata, check that the Original title is set to "The Suite Life of Zack and Cody". Also check jellyfin log, what request are made to [www.podnapisi.net](http://www.podnapisi.net)

Hey, thanks for the fast answer :)

The title for the TV show is correctly defined :

![image](https://user-images.githubusercontent.com/29106016/228665719-751fe5d5-0c5a-47d1-9f4b-c927cd9d8be7.png)

And it is the same for each episode :

![image](https://user-images.githubusercontent.com/29106016/228665869-905fdf5e-2221-4f4f-a2ce-3084981fefca.png)

Here are Jellyfin logs when searching for subtitles :

```
[21:01:24] [INF] [22] subbuzz.Providers.SubBuzz: subs.sab.bz: Request subtitle for 'The Suite Life of Zack & Cody 01x01', language=en, year=2005, IMDB=tt0426371
[21:01:24] [INF] [22] subbuzz.Providers.SubBuzz: subs.sab.bz: GET: http://subs.sab.bz/index.php?act=search&movie=01x01&select-language=1&upldr=&yr=&&release=&imdb=tt0426371&sort=dd&
[21:01:24] [INF] [22] subbuzz.Providers.SubBuzz: subs.sab.bz: POST: http://subs.sab.bz/index.php? -> The Suite Life of Zack & Cody 01x01
[21:01:24] [INF] [22] subbuzz.Providers.SubBuzz: subs.sab.bz: POST: http://subs.sab.bz/index.php? -> The Suite Life of Zack & Cody Season 1
[21:01:24] [INF] [22] subbuzz.Providers.SubBuzz: subsunacs.net: Request subtitle for 'The Suite Life of Zack & Cody 01x01', language=en, year=2005
[21:01:24] [INF] [22] subbuzz.Providers.SubBuzz: subsunacs.net: POST: https://subsunacs.net/search.php -> The Suite Life of Zack & Cody 01x01
[21:01:24] [INF] [22] subbuzz.Providers.SubBuzz: subsunacs.net: POST: https://subsunacs.net/search.php -> The Suite Life of Zack & Cody 01 Season
[21:01:24] [INF] [22] subbuzz.Providers.SubBuzz: yavka.net: Request subtitle for 'The Suite Life of Zack & Cody s01e01', language=en, year=2005
[21:01:24] [INF] [22] subbuzz.Providers.SubBuzz: yavka.net: GET: https://yavka.net/subtitles.php?s=s01e01&y=&c=&u=&l=EN&g=&i=tt0426371
[21:01:24] [INF] [22] subbuzz.Providers.SubBuzz: yavka.net: GET: https://yavka.net/subtitles.php?s=The+Suite+Life+of+Zack+%26+Cody+s01e01&y=&c=&u=&l=EN&g=&i=
[21:01:24] [INF] [22] subbuzz.Providers.SubBuzz: yavka.net: GET: https://yavka.net/subtitles.php?s=The+Suite+Life+of+Zack+%26+Cody+s01&y=&c=&u=&l=EN&g=&i=
[21:01:24] [INF] [22] subbuzz.Providers.SubBuzz: opensubtitles.com: Request subtitle for 'The Suite Life of Zack & Cody', language=en, year=2005, IMDB=tt0426371
[21:01:24] [INF] [22] subbuzz.Providers.SubBuzz: Podnapisi.NET: Request subtitle for 'The Suite Life of Zack & Cody S01E01', language=en, year=2005
[21:01:24] [INF] [22] subbuzz.Providers.SubBuzz: Podnapisi.NET: GET: https://www.podnapisi.net/subtitles/search/old?sXML=1&sL=en&sK=The+Suite+Life+of+Zack+%26+Cody&sTS=1&sTE=1
[21:01:24] [INF] [22] subbuzz.Providers.SubBuzz: Subf2m: Request subtitle for 'The Suite Life of Zack & Cody - First Season', language=en, year=2005
[21:01:24] [INF] [22] subbuzz.Providers.SubBuzz: Subf2m: GET: https://subf2m.co/subtitles/searchbytitle?query=The+Suite+Life+of+Zack+%26+Cody+-+First+Season&l=
[21:01:24] [INF] [22] subbuzz.Providers.SubBuzz: Subscene: Request subtitle for 'The Suite Life of Zack & Cody - First Season', language=en, year=2005
[21:01:24] [INF] [22] subbuzz.Providers.SubBuzz: Subscene: GET: https://subscene.com/subtitles/searchbytitle?query=The+Suite+Life+of+Zack+%26+Cody+-+First+Season&l=
[21:01:24] [INF] [11] subbuzz.Providers.SubBuzz: subsunacs.net: Search duration: 0.384 sec. Subtitles found: 0
[21:01:24] [INF] [10] subbuzz.Providers.SubBuzz: yavka.net: Search duration: 0.366 sec. Subtitles found: 0
[21:01:24] [INF] [27] subbuzz.Providers.SubBuzz: opensubtitles.com: Search duration: 0.431 sec. Subtitles found: 0
[21:01:24] [ERR] [28] subbuzz.Providers.SubBuzz: Podnapisi.NET: GET: https://www.podnapisi.net/subtitles/search/old?sXML=1&sL=en&sK=The+Suite+Life+of+Zack+%26+Cody&sTS=1&sTE=1: Search error: System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception.
 ---> System.Security.Authentication.AuthenticationException: Authentication failed, see inner exception.
 ---> Interop+OpenSsl+SslException: SSL Handshake failed with OpenSSL error - SSL_ERROR_SSL.
 ---> Interop+Crypto+OpenSslCryptographicException: error:0A000172:SSL routines::wrong signature type
   --- End of inner exception stack trace ---
   at Interop.OpenSsl.DoSslHandshake(SafeSslHandle context, ReadOnlySpan`1 input, Byte[]& sendBuf, Int32& sendCount)
   at System.Net.Security.SslStreamPal.HandshakeInternal(SafeFreeCredentials credential, SafeDeleteSslContext& context, ReadOnlySpan`1 inputBuffer, Byte[]& outputBuffer, SslAuthenticationOptions sslAuthenticationOptions)
   --- End of inner exception stack trace ---
   at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](TIOAdapter adapter, Boolean receiveFirst, Byte[] reAuthenticationData, Boolean isApm)
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsync(SslClientAuthenticationOptions sslOptions, HttpRequestMessage request, Boolean async, Stream stream, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsync(SslClientAuthenticationOptions sslOptions, HttpRequestMessage request, Boolean async, Stream stream, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(HttpRequestMessage request)
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.DiagnosticsHandler.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at Microsoft.Extensions.Http.Logging.LoggingHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at Microsoft.Extensions.Http.Logging.LoggingScopeHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at subbuzz.Helpers.Download.Get(String link, String referer, Dictionary`2 post_params, CancellationToken cancellationToken, Int32 maxRetry)
   at subbuzz.Helpers.Download.GetStream(String link, String referer, Dictionary`2 post_params, CancellationToken cancellationToken, Int32 maxRetry)
   at subbuzz.Providers.PodnapisiNet.SearchUrl(String url, SearchInfo si, CancellationToken cancellationToken)
System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception.
 ---> System.Security.Authentication.AuthenticationException: Authentication failed, see inner exception.
 ---> Interop+OpenSsl+SslException: SSL Handshake failed with OpenSSL error - SSL_ERROR_SSL.
 ---> Interop+Crypto+OpenSslCryptographicException: error:0A000172:SSL routines::wrong signature type
   --- End of inner exception stack trace ---
   at Interop.OpenSsl.DoSslHandshake(SafeSslHandle context, ReadOnlySpan`1 input, Byte[]& sendBuf, Int32& sendCount)
   at System.Net.Security.SslStreamPal.HandshakeInternal(SafeFreeCredentials credential, SafeDeleteSslContext& context, ReadOnlySpan`1 inputBuffer, Byte[]& outputBuffer, SslAuthenticationOptions sslAuthenticationOptions)
   --- End of inner exception stack trace ---
   at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](TIOAdapter adapter, Boolean receiveFirst, Byte[] reAuthenticationData, Boolean isApm)
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsync(SslClientAuthenticationOptions sslOptions, HttpRequestMessage request, Boolean async, Stream stream, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsync(SslClientAuthenticationOptions sslOptions, HttpRequestMessage request, Boolean async, Stream stream, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(HttpRequestMessage request)
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.DiagnosticsHandler.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at Microsoft.Extensions.Http.Logging.LoggingHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at Microsoft.Extensions.Http.Logging.LoggingScopeHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at subbuzz.Helpers.Download.Get(String link, String referer, Dictionary`2 post_params, CancellationToken cancellationToken, Int32 maxRetry)
   at subbuzz.Helpers.Download.GetStream(String link, String referer, Dictionary`2 post_params, CancellationToken cancellationToken, Int32 maxRetry)
   at subbuzz.Providers.PodnapisiNet.SearchUrl(String url, SearchInfo si, CancellationToken cancellationToken)
[21:01:24] [INF] [28] subbuzz.Providers.SubBuzz: Podnapisi.NET: Search duration: 0.127 sec. Subtitles found: 0
[21:01:24] [INF] [28] subbuzz.Providers.SubBuzz: Subf2m: Search duration: 0.203 sec. Subtitles found: 0
[21:01:24] [INF] [28] subbuzz.Providers.SubBuzz: Subscene: Search duration: 0.247 sec. Subtitles found: 0
[21:01:52] [INF] [22] subbuzz.Providers.SubBuzz: subbuzz: The response from subs.sab.bz is ignored because it did not complete in time.
[21:01:52] [INF] [22] subbuzz.Providers.SubBuzz: subbuzz: Search duration: 29.001 sec. Subtitles found: 0
[21:01:52] [WRN] [22] Jellyfin.Server.Middleware.ResponseTimeMiddleware: Slow HTTP Response from http://141.145.216.80:8096/Items/8979fbb1649574c131d6cd6616fbbf54/RemoteSearch/Subtitles/eng to 176.133.158.232 in 0:00:29.0975795 with Status Code 200
[21:01:54] [ERR] [22] subbuzz.Providers.SubBuzz: subs.sab.bz: GET: http://subs.sab.bz/index.php?act=search&movie=01x01&select-language=1&upldr=&yr=&&release=&imdb=tt0426371&sort=dd&: Search error: System.Threading.Tasks.TaskCanceledException: The request was canceled due to the configured HttpClient.Timeout of 30 seconds elapsing.
 ---> System.TimeoutException: A task was canceled.
 ---> System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.DiagnosticsHandler.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at Microsoft.Extensions.Http.Logging.LoggingHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at Microsoft.Extensions.Http.Logging.LoggingScopeHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   --- End of inner exception stack trace ---
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpClient.HandleFailure(Exception e, Boolean telemetryStarted, HttpResponseMessage response, CancellationTokenSource cts, CancellationToken cancellationToken, CancellationTokenSource pendingRequestsCts)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at subbuzz.Helpers.Download.Get(String link, String referer, Dictionary`2 post_params, CancellationToken cancellationToken, Int32 maxRetry)
   at subbuzz.Helpers.Download.GetStream(String link, String referer, Dictionary`2 post_params, CancellationToken cancellationToken, Int32 maxRetry)
   at subbuzz.Providers.SubsSabBz.SearchUrl(String url, Dictionary`2 post_params, SearchInfo si, CancellationToken cancellationToken)
System.Threading.Tasks.TaskCanceledException: The request was canceled due to the configured HttpClient.Timeout of 30 seconds elapsing.
 ---> System.TimeoutException: A task was canceled.
 ---> System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.DiagnosticsHandler.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at Microsoft.Extensions.Http.Logging.LoggingHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at Microsoft.Extensions.Http.Logging.LoggingScopeHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   --- End of inner exception stack trace ---
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpClient.HandleFailure(Exception e, Boolean telemetryStarted, HttpResponseMessage response, CancellationTokenSource cts, CancellationToken cancellationToken, CancellationTokenSource pendingRequestsCts)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at subbuzz.Helpers.Download.Get(String link, String referer, Dictionary`2 post_params, CancellationToken cancellationToken, Int32 maxRetry)
   at subbuzz.Helpers.Download.GetStream(String link, String referer, Dictionary`2 post_params, CancellationToken cancellationToken, Int32 maxRetry)
   at subbuzz.Providers.SubsSabBz.SearchUrl(String url, Dictionary`2 post_params, SearchInfo si, CancellationToken cancellationToken)
[21:01:54] [ERR] [28] subbuzz.Providers.SubBuzz: subs.sab.bz: GET: http://subs.sab.bz/index.php?: Search error: System.Threading.Tasks.TaskCanceledException: The request was canceled due to the configured HttpClient.Timeout of 30 seconds elapsing.
 ---> System.TimeoutException: A task was canceled.
 ---> System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.DiagnosticsHandler.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at Microsoft.Extensions.Http.Logging.LoggingHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at Microsoft.Extensions.Http.Logging.LoggingScopeHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   --- End of inner exception stack trace ---
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpClient.HandleFailure(Exception e, Boolean telemetryStarted, HttpResponseMessage response, CancellationTokenSource cts, CancellationToken cancellationToken, CancellationTokenSource pendingRequestsCts)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at subbuzz.Helpers.Download.Get(String link, String referer, Dictionary`2 post_params, CancellationToken cancellationToken, Int32 maxRetry)
   at subbuzz.Helpers.Download.GetStream(String link, String referer, Dictionary`2 post_params, CancellationToken cancellationToken, Int32 maxRetry)
   at subbuzz.Providers.SubsSabBz.SearchUrl(String url, Dictionary`2 post_params, SearchInfo si, CancellationToken cancellationToken)
System.Threading.Tasks.TaskCanceledException: The request was canceled due to the configured HttpClient.Timeout of 30 seconds elapsing.
 ---> System.TimeoutException: A task was canceled.
 ---> System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.DiagnosticsHandler.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at Microsoft.Extensions.Http.Logging.LoggingHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at Microsoft.Extensions.Http.Logging.LoggingScopeHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   --- End of inner exception stack trace ---
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpClient.HandleFailure(Exception e, Boolean telemetryStarted, HttpResponseMessage response, CancellationTokenSource cts, CancellationToken cancellationToken, CancellationTokenSource pendingRequestsCts)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at subbuzz.Helpers.Download.Get(String link, String referer, Dictionary`2 post_params, CancellationToken cancellationToken, Int32 maxRetry)
   at subbuzz.Helpers.Download.GetStream(String link, String referer, Dictionary`2 post_params, CancellationToken cancellationToken, Int32 maxRetry)
   at subbuzz.Providers.SubsSabBz.SearchUrl(String url, Dictionary`2 post_params, SearchInfo si, CancellationToken cancellationToken)
[21:01:54] [ERR] [22] subbuzz.Providers.SubBuzz: subs.sab.bz: GET: http://subs.sab.bz/index.php?: Search error: System.Threading.Tasks.TaskCanceledException: The request was canceled due to the configured HttpClient.Timeout of 30 seconds elapsing.
 ---> System.TimeoutException: A task was canceled.
 ---> System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.DiagnosticsHandler.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at Microsoft.Extensions.Http.Logging.LoggingHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at Microsoft.Extensions.Http.Logging.LoggingScopeHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   --- End of inner exception stack trace ---
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpClient.HandleFailure(Exception e, Boolean telemetryStarted, HttpResponseMessage response, CancellationTokenSource cts, CancellationToken cancellationToken, CancellationTokenSource pendingRequestsCts)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at subbuzz.Helpers.Download.Get(String link, String referer, Dictionary`2 post_params, CancellationToken cancellationToken, Int32 maxRetry)
   at subbuzz.Helpers.Download.GetStream(String link, String referer, Dictionary`2 post_params, CancellationToken cancellationToken, Int32 maxRetry)
   at subbuzz.Providers.SubsSabBz.SearchUrl(String url, Dictionary`2 post_params, SearchInfo si, CancellationToken cancellationToken)
System.Threading.Tasks.TaskCanceledException: The request was canceled due to the configured HttpClient.Timeout of 30 seconds elapsing.
 ---> System.TimeoutException: A task was canceled.
 ---> System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.DiagnosticsHandler.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at Microsoft.Extensions.Http.Logging.LoggingHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at Microsoft.Extensions.Http.Logging.LoggingScopeHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   --- End of inner exception stack trace ---
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpClient.HandleFailure(Exception e, Boolean telemetryStarted, HttpResponseMessage response, CancellationTokenSource cts, CancellationToken cancellationToken, CancellationTokenSource pendingRequestsCts)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at subbuzz.Helpers.Download.Get(String link, String referer, Dictionary`2 post_params, CancellationToken cancellationToken, Int32 maxRetry)
   at subbuzz.Helpers.Download.GetStream(String link, String referer, Dictionary`2 post_params, CancellationToken cancellationToken, Int32 maxRetry)
   at subbuzz.Providers.SubsSabBz.SearchUrl(String url, Dictionary`2 post_params, SearchInfo si, CancellationToken cancellationToken)
[21:01:54] [INF] [22] subbuzz.Providers.SubBuzz: subs.sab.bz: Search duration: 30.758 sec. Subtitles found: 0
```

**Comment by josdion** [comment]
The error is 
`
System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception.
 ---> System.Security.Authentication.AuthenticationException: Authentication failed, see inner exception.
 ---> Interop+OpenSsl+SslException: SSL Handshake failed with OpenSSL error - SSL_ERROR_SSL.
 ---> Interop+Crypto+OpenSslCryptographicException: error:0A000172:SSL routines::wrong signature type
`

Please check #2 for a workaround - https://github.com/josdion/subbuzz/issues/2#issuecomment-1342282232, the issue is the same.  

Also you can consider disabling subs.sab.bz provider to get faster responses.

**Comment by PaulGitProject** [comment]
> The error is `System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception. ---> System.Security.Authentication.AuthenticationException: Authentication failed, see inner exception. ---> Interop+OpenSsl+SslException: SSL Handshake failed with OpenSSL error - SSL_ERROR_SSL. ---> Interop+Crypto+OpenSslCryptographicException: error:0A000172:SSL routines::wrong signature type`
> 
> Please check #2 for a workaround - [#2 (comment)](https://github.com/josdion/subbuzz/issues/2#issuecomment-1342282232), the issue is the same.
> 
> Also you can consider disabling subs.sab.bz provider to get faster responses.

Is it the same if Jellyfin is running in a docker? Do i need to just edit /etc/ssl/openconf?

**Comment by josdion** [comment]
The file should be the same, but you should edit the one that is inside your docker container. Maybe you can try to mount the file to some external file and edit the external one.
